// Code generated by "enumer -type=Color"; DO NOT EDIT.

package mage

import (
	"fmt"
	"strings"
)

const _ColorName = "ColorlessWhiteBlueBlackRedGreen"

var _ColorIndex = [...]uint8{0, 9, 14, 18, 23, 26, 31}

const _ColorLowerName = "colorlesswhiteblueblackredgreen"

func (i Color) String() string {
	if i < 0 || i >= Color(len(_ColorIndex)-1) {
		return fmt.Sprintf("Color(%d)", i)
	}
	return _ColorName[_ColorIndex[i]:_ColorIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ColorNoOp() {
	var x [1]struct{}
	_ = x[Colorless-(0)]
	_ = x[White-(1)]
	_ = x[Blue-(2)]
	_ = x[Black-(3)]
	_ = x[Red-(4)]
	_ = x[Green-(5)]
}

var _ColorValues = []Color{Colorless, White, Blue, Black, Red, Green}

var _ColorNameToValueMap = map[string]Color{
	_ColorName[0:9]:        Colorless,
	_ColorLowerName[0:9]:   Colorless,
	_ColorName[9:14]:       White,
	_ColorLowerName[9:14]:  White,
	_ColorName[14:18]:      Blue,
	_ColorLowerName[14:18]: Blue,
	_ColorName[18:23]:      Black,
	_ColorLowerName[18:23]: Black,
	_ColorName[23:26]:      Red,
	_ColorLowerName[23:26]: Red,
	_ColorName[26:31]:      Green,
	_ColorLowerName[26:31]: Green,
}

var _ColorNames = []string{
	_ColorName[0:9],
	_ColorName[9:14],
	_ColorName[14:18],
	_ColorName[18:23],
	_ColorName[23:26],
	_ColorName[26:31],
}

// ColorString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ColorString(s string) (Color, error) {
	if val, ok := _ColorNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ColorNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Color values", s)
}

// ColorValues returns all values of the enum
func ColorValues() []Color {
	return _ColorValues
}

// ColorStrings returns a slice of all String values of the enum
func ColorStrings() []string {
	strs := make([]string, len(_ColorNames))
	copy(strs, _ColorNames)
	return strs
}

// IsAColor returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Color) IsAColor() bool {
	for _, v := range _ColorValues {
		if i == v {
			return true
		}
	}
	return false
}
