// Code generated by "enumer -type=Duration"; DO NOT EDIT.

package mage

import (
	"fmt"
	"strings"
)

const _DurationName = "WhileOnBattlefieldEndOfTurnEndOfCombatUntilYourNextTurnIndefinite"

var _DurationIndex = [...]uint8{0, 18, 27, 38, 55, 65}

const _DurationLowerName = "whileonbattlefieldendofturnendofcombatuntilyournextturnindefinite"

func (i Duration) String() string {
	if i < 0 || i >= Duration(len(_DurationIndex)-1) {
		return fmt.Sprintf("Duration(%d)", i)
	}
	return _DurationName[_DurationIndex[i]:_DurationIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DurationNoOp() {
	var x [1]struct{}
	_ = x[WhileOnBattlefield-(0)]
	_ = x[EndOfTurn-(1)]
	_ = x[EndOfCombat-(2)]
	_ = x[UntilYourNextTurn-(3)]
	_ = x[Indefinite-(4)]
}

var _DurationValues = []Duration{WhileOnBattlefield, EndOfTurn, EndOfCombat, UntilYourNextTurn, Indefinite}

var _DurationNameToValueMap = map[string]Duration{
	_DurationName[0:18]:       WhileOnBattlefield,
	_DurationLowerName[0:18]:  WhileOnBattlefield,
	_DurationName[18:27]:      EndOfTurn,
	_DurationLowerName[18:27]: EndOfTurn,
	_DurationName[27:38]:      EndOfCombat,
	_DurationLowerName[27:38]: EndOfCombat,
	_DurationName[38:55]:      UntilYourNextTurn,
	_DurationLowerName[38:55]: UntilYourNextTurn,
	_DurationName[55:65]:      Indefinite,
	_DurationLowerName[55:65]: Indefinite,
}

var _DurationNames = []string{
	_DurationName[0:18],
	_DurationName[18:27],
	_DurationName[27:38],
	_DurationName[38:55],
	_DurationName[55:65],
}

// DurationString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DurationString(s string) (Duration, error) {
	if val, ok := _DurationNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DurationNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Duration values", s)
}

// DurationValues returns all values of the enum
func DurationValues() []Duration {
	return _DurationValues
}

// DurationStrings returns a slice of all String values of the enum
func DurationStrings() []string {
	strs := make([]string, len(_DurationNames))
	copy(strs, _DurationNames)
	return strs
}

// IsADuration returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Duration) IsADuration() bool {
	for _, v := range _DurationValues {
		if i == v {
			return true
		}
	}
	return false
}
