// Code generated by "enumer -type=Layer,Duration -trimprefix=Layer -output=effect_manager_enumer.go"; DO NOT EDIT.

package mage

import (
	"fmt"
	"strings"
)

const _LayerName = "CopyControlTextTypeColorAbilityPT"

var _LayerIndex = [...]uint8{0, 4, 11, 15, 19, 24, 31, 33}

const _LayerLowerName = "copycontroltexttypecolorabilitypt"

func (i Layer) String() string {
	i -= 1
	if i < 0 || i >= Layer(len(_LayerIndex)-1) {
		return fmt.Sprintf("Layer(%d)", i+1)
	}
	return _LayerName[_LayerIndex[i]:_LayerIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _LayerNoOp() {
	var x [1]struct{}
	_ = x[LayerCopy-(1)]
	_ = x[LayerControl-(2)]
	_ = x[LayerText-(3)]
	_ = x[LayerType-(4)]
	_ = x[LayerColor-(5)]
	_ = x[LayerAbility-(6)]
	_ = x[LayerPT-(7)]
}

var _LayerValues = []Layer{LayerCopy, LayerControl, LayerText, LayerType, LayerColor, LayerAbility, LayerPT}

var _LayerNameToValueMap = map[string]Layer{
	_LayerName[0:4]:        LayerCopy,
	_LayerLowerName[0:4]:   LayerCopy,
	_LayerName[4:11]:       LayerControl,
	_LayerLowerName[4:11]:  LayerControl,
	_LayerName[11:15]:      LayerText,
	_LayerLowerName[11:15]: LayerText,
	_LayerName[15:19]:      LayerType,
	_LayerLowerName[15:19]: LayerType,
	_LayerName[19:24]:      LayerColor,
	_LayerLowerName[19:24]: LayerColor,
	_LayerName[24:31]:      LayerAbility,
	_LayerLowerName[24:31]: LayerAbility,
	_LayerName[31:33]:      LayerPT,
	_LayerLowerName[31:33]: LayerPT,
}

var _LayerNames = []string{
	_LayerName[0:4],
	_LayerName[4:11],
	_LayerName[11:15],
	_LayerName[15:19],
	_LayerName[19:24],
	_LayerName[24:31],
	_LayerName[31:33],
}

// LayerString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func LayerString(s string) (Layer, error) {
	if val, ok := _LayerNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _LayerNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Layer values", s)
}

// LayerValues returns all values of the enum
func LayerValues() []Layer {
	return _LayerValues
}

// LayerStrings returns a slice of all String values of the enum
func LayerStrings() []string {
	strs := make([]string, len(_LayerNames))
	copy(strs, _LayerNames)
	return strs
}

// IsALayer returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Layer) IsALayer() bool {
	for _, v := range _LayerValues {
		if i == v {
			return true
		}
	}
	return false
}

const _DurationName = "WhileOnBattlefieldEndOfTurnEndOfCombatUntilYourNextTurnIndefinite"

var _DurationIndex = [...]uint8{0, 18, 27, 38, 55, 65}

const _DurationLowerName = "whileonbattlefieldendofturnendofcombatuntilyournextturnindefinite"

func (i Duration) String() string {
	if i < 0 || i >= Duration(len(_DurationIndex)-1) {
		return fmt.Sprintf("Duration(%d)", i)
	}
	return _DurationName[_DurationIndex[i]:_DurationIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DurationNoOp() {
	var x [1]struct{}
	_ = x[WhileOnBattlefield-(0)]
	_ = x[EndOfTurn-(1)]
	_ = x[EndOfCombat-(2)]
	_ = x[UntilYourNextTurn-(3)]
	_ = x[Indefinite-(4)]
}

var _DurationValues = []Duration{WhileOnBattlefield, EndOfTurn, EndOfCombat, UntilYourNextTurn, Indefinite}

var _DurationNameToValueMap = map[string]Duration{
	_DurationName[0:18]:       WhileOnBattlefield,
	_DurationLowerName[0:18]:  WhileOnBattlefield,
	_DurationName[18:27]:      EndOfTurn,
	_DurationLowerName[18:27]: EndOfTurn,
	_DurationName[27:38]:      EndOfCombat,
	_DurationLowerName[27:38]: EndOfCombat,
	_DurationName[38:55]:      UntilYourNextTurn,
	_DurationLowerName[38:55]: UntilYourNextTurn,
	_DurationName[55:65]:      Indefinite,
	_DurationLowerName[55:65]: Indefinite,
}

var _DurationNames = []string{
	_DurationName[0:18],
	_DurationName[18:27],
	_DurationName[27:38],
	_DurationName[38:55],
	_DurationName[55:65],
}

// DurationString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DurationString(s string) (Duration, error) {
	if val, ok := _DurationNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DurationNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Duration values", s)
}

// DurationValues returns all values of the enum
func DurationValues() []Duration {
	return _DurationValues
}

// DurationStrings returns a slice of all String values of the enum
func DurationStrings() []string {
	strs := make([]string, len(_DurationNames))
	copy(strs, _DurationNames)
	return strs
}

// IsADuration returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Duration) IsADuration() bool {
	for _, v := range _DurationValues {
		if i == v {
			return true
		}
	}
	return false
}
