// Code generated by "enumer -type=Layer -trimprefix=Layer"; DO NOT EDIT.

package mage

import (
	"fmt"
	"strings"
)

const _LayerName = "CopyControlTextTypeColorAbilityPT"

var _LayerIndex = [...]uint8{0, 4, 11, 15, 19, 24, 31, 33}

const _LayerLowerName = "copycontroltexttypecolorabilitypt"

func (i Layer) String() string {
	i -= 1
	if i < 0 || i >= Layer(len(_LayerIndex)-1) {
		return fmt.Sprintf("Layer(%d)", i+1)
	}
	return _LayerName[_LayerIndex[i]:_LayerIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _LayerNoOp() {
	var x [1]struct{}
	_ = x[LayerCopy-(1)]
	_ = x[LayerControl-(2)]
	_ = x[LayerText-(3)]
	_ = x[LayerType-(4)]
	_ = x[LayerColor-(5)]
	_ = x[LayerAbility-(6)]
	_ = x[LayerPT-(7)]
}

var _LayerValues = []Layer{LayerCopy, LayerControl, LayerText, LayerType, LayerColor, LayerAbility, LayerPT}

var _LayerNameToValueMap = map[string]Layer{
	_LayerName[0:4]:        LayerCopy,
	_LayerLowerName[0:4]:   LayerCopy,
	_LayerName[4:11]:       LayerControl,
	_LayerLowerName[4:11]:  LayerControl,
	_LayerName[11:15]:      LayerText,
	_LayerLowerName[11:15]: LayerText,
	_LayerName[15:19]:      LayerType,
	_LayerLowerName[15:19]: LayerType,
	_LayerName[19:24]:      LayerColor,
	_LayerLowerName[19:24]: LayerColor,
	_LayerName[24:31]:      LayerAbility,
	_LayerLowerName[24:31]: LayerAbility,
	_LayerName[31:33]:      LayerPT,
	_LayerLowerName[31:33]: LayerPT,
}

var _LayerNames = []string{
	_LayerName[0:4],
	_LayerName[4:11],
	_LayerName[11:15],
	_LayerName[15:19],
	_LayerName[19:24],
	_LayerName[24:31],
	_LayerName[31:33],
}

// LayerString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func LayerString(s string) (Layer, error) {
	if val, ok := _LayerNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _LayerNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Layer values", s)
}

// LayerValues returns all values of the enum
func LayerValues() []Layer {
	return _LayerValues
}

// LayerStrings returns a slice of all String values of the enum
func LayerStrings() []string {
	strs := make([]string, len(_LayerNames))
	copy(strs, _LayerNames)
	return strs
}

// IsALayer returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Layer) IsALayer() bool {
	for _, v := range _LayerValues {
		if i == v {
			return true
		}
	}
	return false
}
