// Code generated by "enumer -type=AbilityType -trimprefix=Ability -output=abilitytype_enumer.go"; DO NOT EDIT.

package core

import (
	"fmt"
	"strings"
)

const _AbilityTypeName = "SpellActivatedTriggeredManaStatic"

var _AbilityTypeIndex = [...]uint8{0, 5, 14, 23, 27, 33}

const _AbilityTypeLowerName = "spellactivatedtriggeredmanastatic"

func (i AbilityType) String() string {
	if i < 0 || i >= AbilityType(len(_AbilityTypeIndex)-1) {
		return fmt.Sprintf("AbilityType(%d)", i)
	}
	return _AbilityTypeName[_AbilityTypeIndex[i]:_AbilityTypeIndex[i+1]]
}

func _AbilityTypeNoOp() {
	var x [1]struct{}
	_ = x[AbilitySpell-(0)]
	_ = x[AbilityActivated-(1)]
	_ = x[AbilityTriggered-(2)]
	_ = x[AbilityMana-(3)]
	_ = x[AbilityStatic-(4)]
}

var _AbilityTypeValues = []AbilityType{AbilitySpell, AbilityActivated, AbilityTriggered, AbilityMana, AbilityStatic}

var _AbilityTypeNameToValueMap = map[string]AbilityType{
	_AbilityTypeName[0:5]:        AbilitySpell,
	_AbilityTypeLowerName[0:5]:   AbilitySpell,
	_AbilityTypeName[5:14]:       AbilityActivated,
	_AbilityTypeLowerName[5:14]:  AbilityActivated,
	_AbilityTypeName[14:23]:      AbilityTriggered,
	_AbilityTypeLowerName[14:23]: AbilityTriggered,
	_AbilityTypeName[23:27]:      AbilityMana,
	_AbilityTypeLowerName[23:27]: AbilityMana,
	_AbilityTypeName[27:33]:      AbilityStatic,
	_AbilityTypeLowerName[27:33]: AbilityStatic,
}

var _AbilityTypeNames = []string{
	_AbilityTypeName[0:5],
	_AbilityTypeName[5:14],
	_AbilityTypeName[14:23],
	_AbilityTypeName[23:27],
	_AbilityTypeName[27:33],
}

func AbilityTypeString(s string) (AbilityType, error) {
	if val, ok := _AbilityTypeNameToValueMap[s]; ok {
		return val, nil
	}
	if val, ok := _AbilityTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AbilityType values", s)
}

func AbilityTypeValues() []AbilityType {
	return _AbilityTypeValues
}

func AbilityTypeStrings() []string {
	strs := make([]string, len(_AbilityTypeNames))
	copy(strs, _AbilityTypeNames)
	return strs
}

func (i AbilityType) IsAAbilityType() bool {
	for _, v := range _AbilityTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
