// Code generated by "enumer -type=CardType -trimprefix=Type -output=cardtype_enumer.go"; DO NOT EDIT.

package core

import (
	"fmt"
	"strings"
)

const _CardTypeName = "CreatureInstantSorceryLandArtifactEnchantment"

var _CardTypeIndex = [...]uint8{0, 8, 15, 22, 26, 34, 45}

const _CardTypeLowerName = "creatureinstantsorcerylandartifactenchantment"

func (i CardType) String() string {
	if i < 0 || i >= CardType(len(_CardTypeIndex)-1) {
		return fmt.Sprintf("CardType(%d)", i)
	}
	return _CardTypeName[_CardTypeIndex[i]:_CardTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _CardTypeNoOp() {
	var x [1]struct{}
	_ = x[TypeCreature-(0)]
	_ = x[TypeInstant-(1)]
	_ = x[TypeSorcery-(2)]
	_ = x[TypeLand-(3)]
	_ = x[TypeArtifact-(4)]
	_ = x[TypeEnchantment-(5)]
}

var _CardTypeValues = []CardType{TypeCreature, TypeInstant, TypeSorcery, TypeLand, TypeArtifact, TypeEnchantment}

var _CardTypeNameToValueMap = map[string]CardType{
	_CardTypeName[0:8]:        TypeCreature,
	_CardTypeLowerName[0:8]:   TypeCreature,
	_CardTypeName[8:15]:       TypeInstant,
	_CardTypeLowerName[8:15]:  TypeInstant,
	_CardTypeName[15:22]:      TypeSorcery,
	_CardTypeLowerName[15:22]: TypeSorcery,
	_CardTypeName[22:26]:      TypeLand,
	_CardTypeLowerName[22:26]: TypeLand,
	_CardTypeName[26:34]:      TypeArtifact,
	_CardTypeLowerName[26:34]: TypeArtifact,
	_CardTypeName[34:45]:      TypeEnchantment,
	_CardTypeLowerName[34:45]: TypeEnchantment,
}

var _CardTypeNames = []string{
	_CardTypeName[0:8],
	_CardTypeName[8:15],
	_CardTypeName[15:22],
	_CardTypeName[22:26],
	_CardTypeName[26:34],
	_CardTypeName[34:45],
}

// CardTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CardTypeString(s string) (CardType, error) {
	if val, ok := _CardTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _CardTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CardType values", s)
}

// CardTypeValues returns all values of the enum
func CardTypeValues() []CardType {
	return _CardTypeValues
}

// CardTypeStrings returns a slice of all String values of the enum
func CardTypeStrings() []string {
	strs := make([]string, len(_CardTypeNames))
	copy(strs, _CardTypeNames)
	return strs
}

// IsACardType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CardType) IsACardType() bool {
	for _, v := range _CardTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
