// Code generated by "enumer -type=EventType -trimprefix=Evt -output=event_enumer.go"; DO NOT EDIT.

package core

import (
	"fmt"
	"strings"
)

const _EventTypeName = "ZoneChangeCreatureDiedEntersBattlefieldLeavesBattlefieldDeclaredAttackerDeclaredBlockerDamageDealtLifeGainedLifeLostCardDrawnSpellCastAbilityActivatedAttachDetachPutIntoGraveyardFromBattlefieldUpkeepDrawStepBeginCombatEndStepTappedLandPlayedBlockersDeclEndOfCombatBecameUntappedMainPhaseCleanupCreatureBlocks"

var _EventTypeIndex = [...]uint16{0, 10, 22, 39, 56, 72, 87, 98, 108, 116, 125, 134, 150, 156, 162, 193, 199, 207, 218, 225, 231, 241, 253, 264, 278, 287, 294, 308}

const _EventTypeLowerName = "zonechangecreaturediedentersbattlefieldleavesbattlefielddeclaredattackerdeclaredblockerdamagedealtlifegainedlifelostcarddrawnspellcastabilityactivatedattachdetachputintograveyardfrombattlefieldupkeepdrawstepbegincombatendsteptappedlandplayedblockersdeclendofcombatbecameuntappedmainphasecleanupcreatureblocks"

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(_EventTypeIndex)-1) {
		return fmt.Sprintf("EventType(%d)", i)
	}
	return _EventTypeName[_EventTypeIndex[i]:_EventTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _EventTypeNoOp() {
	var x [1]struct{}
	_ = x[EvtZoneChange-(0)]
	_ = x[EvtCreatureDied-(1)]
	_ = x[EvtEntersBattlefield-(2)]
	_ = x[EvtLeavesBattlefield-(3)]
	_ = x[EvtDeclaredAttacker-(4)]
	_ = x[EvtDeclaredBlocker-(5)]
	_ = x[EvtDamageDealt-(6)]
	_ = x[EvtLifeGained-(7)]
	_ = x[EvtLifeLost-(8)]
	_ = x[EvtCardDrawn-(9)]
	_ = x[EvtSpellCast-(10)]
	_ = x[EvtAbilityActivated-(11)]
	_ = x[EvtAttach-(12)]
	_ = x[EvtDetach-(13)]
	_ = x[EvtPutIntoGraveyardFromBattlefield-(14)]
	_ = x[EvtUpkeep-(15)]
	_ = x[EvtDrawStep-(16)]
	_ = x[EvtBeginCombat-(17)]
	_ = x[EvtEndStep-(18)]
	_ = x[EvtTapped-(19)]
	_ = x[EvtLandPlayed-(20)]
	_ = x[EvtBlockersDecl-(21)]
	_ = x[EvtEndOfCombat-(22)]
	_ = x[EvtBecameUntapped-(23)]
	_ = x[EvtMainPhase-(24)]
	_ = x[EvtCleanup-(25)]
	_ = x[EvtCreatureBlocks-(26)]
}

var _EventTypeValues = []EventType{EvtZoneChange, EvtCreatureDied, EvtEntersBattlefield, EvtLeavesBattlefield, EvtDeclaredAttacker, EvtDeclaredBlocker, EvtDamageDealt, EvtLifeGained, EvtLifeLost, EvtCardDrawn, EvtSpellCast, EvtAbilityActivated, EvtAttach, EvtDetach, EvtPutIntoGraveyardFromBattlefield, EvtUpkeep, EvtDrawStep, EvtBeginCombat, EvtEndStep, EvtTapped, EvtLandPlayed, EvtBlockersDecl, EvtEndOfCombat, EvtBecameUntapped, EvtMainPhase, EvtCleanup, EvtCreatureBlocks}

var _EventTypeNameToValueMap = map[string]EventType{
	_EventTypeName[0:10]:         EvtZoneChange,
	_EventTypeLowerName[0:10]:    EvtZoneChange,
	_EventTypeName[10:22]:        EvtCreatureDied,
	_EventTypeLowerName[10:22]:   EvtCreatureDied,
	_EventTypeName[22:39]:        EvtEntersBattlefield,
	_EventTypeLowerName[22:39]:   EvtEntersBattlefield,
	_EventTypeName[39:56]:        EvtLeavesBattlefield,
	_EventTypeLowerName[39:56]:   EvtLeavesBattlefield,
	_EventTypeName[56:72]:        EvtDeclaredAttacker,
	_EventTypeLowerName[56:72]:   EvtDeclaredAttacker,
	_EventTypeName[72:87]:        EvtDeclaredBlocker,
	_EventTypeLowerName[72:87]:   EvtDeclaredBlocker,
	_EventTypeName[87:98]:        EvtDamageDealt,
	_EventTypeLowerName[87:98]:   EvtDamageDealt,
	_EventTypeName[98:108]:       EvtLifeGained,
	_EventTypeLowerName[98:108]:  EvtLifeGained,
	_EventTypeName[108:116]:      EvtLifeLost,
	_EventTypeLowerName[108:116]: EvtLifeLost,
	_EventTypeName[116:125]:      EvtCardDrawn,
	_EventTypeLowerName[116:125]: EvtCardDrawn,
	_EventTypeName[125:134]:      EvtSpellCast,
	_EventTypeLowerName[125:134]: EvtSpellCast,
	_EventTypeName[134:150]:      EvtAbilityActivated,
	_EventTypeLowerName[134:150]: EvtAbilityActivated,
	_EventTypeName[150:156]:      EvtAttach,
	_EventTypeLowerName[150:156]: EvtAttach,
	_EventTypeName[156:162]:      EvtDetach,
	_EventTypeLowerName[156:162]: EvtDetach,
	_EventTypeName[162:193]:      EvtPutIntoGraveyardFromBattlefield,
	_EventTypeLowerName[162:193]: EvtPutIntoGraveyardFromBattlefield,
	_EventTypeName[193:199]:      EvtUpkeep,
	_EventTypeLowerName[193:199]: EvtUpkeep,
	_EventTypeName[199:207]:      EvtDrawStep,
	_EventTypeLowerName[199:207]: EvtDrawStep,
	_EventTypeName[207:218]:      EvtBeginCombat,
	_EventTypeLowerName[207:218]: EvtBeginCombat,
	_EventTypeName[218:225]:      EvtEndStep,
	_EventTypeLowerName[218:225]: EvtEndStep,
	_EventTypeName[225:231]:      EvtTapped,
	_EventTypeLowerName[225:231]: EvtTapped,
	_EventTypeName[231:241]:      EvtLandPlayed,
	_EventTypeLowerName[231:241]: EvtLandPlayed,
	_EventTypeName[241:253]:      EvtBlockersDecl,
	_EventTypeLowerName[241:253]: EvtBlockersDecl,
	_EventTypeName[253:264]:      EvtEndOfCombat,
	_EventTypeLowerName[253:264]: EvtEndOfCombat,
	_EventTypeName[264:278]:      EvtBecameUntapped,
	_EventTypeLowerName[264:278]: EvtBecameUntapped,
	_EventTypeName[278:287]:      EvtMainPhase,
	_EventTypeLowerName[278:287]: EvtMainPhase,
	_EventTypeName[287:294]:      EvtCleanup,
	_EventTypeLowerName[287:294]: EvtCleanup,
	_EventTypeName[294:308]:      EvtCreatureBlocks,
	_EventTypeLowerName[294:308]: EvtCreatureBlocks,
}

var _EventTypeNames = []string{
	_EventTypeName[0:10],
	_EventTypeName[10:22],
	_EventTypeName[22:39],
	_EventTypeName[39:56],
	_EventTypeName[56:72],
	_EventTypeName[72:87],
	_EventTypeName[87:98],
	_EventTypeName[98:108],
	_EventTypeName[108:116],
	_EventTypeName[116:125],
	_EventTypeName[125:134],
	_EventTypeName[134:150],
	_EventTypeName[150:156],
	_EventTypeName[156:162],
	_EventTypeName[162:193],
	_EventTypeName[193:199],
	_EventTypeName[199:207],
	_EventTypeName[207:218],
	_EventTypeName[218:225],
	_EventTypeName[225:231],
	_EventTypeName[231:241],
	_EventTypeName[241:253],
	_EventTypeName[253:264],
	_EventTypeName[264:278],
	_EventTypeName[278:287],
	_EventTypeName[287:294],
	_EventTypeName[294:308],
}

// EventTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EventTypeString(s string) (EventType, error) {
	if val, ok := _EventTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _EventTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to EventType values", s)
}

// EventTypeValues returns all values of the enum
func EventTypeValues() []EventType {
	return _EventTypeValues
}

// EventTypeStrings returns a slice of all String values of the enum
func EventTypeStrings() []string {
	strs := make([]string, len(_EventTypeNames))
	copy(strs, _EventTypeNames)
	return strs
}

// IsAEventType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i EventType) IsAEventType() bool {
	for _, v := range _EventTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
