// Code generated by "enumer -type=EventType -trimprefix=Evt -output=event_enumer.go"; DO NOT EDIT.

package core

import (
	"fmt"
	"strings"
)

const _EventTypeName = "ZoneChangeDeclaredAttackerDeclaredBlockerDamageDealtLifeGainedLifeLostCardDrawnSpellCastAbilityActivatedAttachDetachUpkeepDrawStepBeginCombatEndStepTappedLandPlayedBlockersDeclEndOfCombatBecameUntappedMainPhaseCleanupCreatureBlocksEntersAttackingEntersBlockingScryDiscardSacrificeBecomesTargetAttackersDeclaredCombatDamageDealt"

var _EventTypeIndex = [...]uint16{0, 10, 26, 41, 52, 62, 70, 79, 88, 104, 110, 116, 122, 130, 141, 148, 154, 164, 176, 187, 201, 210, 217, 231, 246, 260, 264, 271, 280, 293, 310, 327}

const _EventTypeLowerName = "zonechangedeclaredattackerdeclaredblockerdamagedealtlifegainedlifelostcarddrawnspellcastabilityactivatedattachdetachupkeepdrawstepbegincombatendsteptappedlandplayedblockersdeclendofcombatbecameuntappedmainphasecleanupcreatureblocksentersattackingentersblockingscrydiscardsacrificebecomestargetattackersdeclaredcombatdamagedealt"

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(_EventTypeIndex)-1) {
		return fmt.Sprintf("EventType(%d)", i)
	}
	return _EventTypeName[_EventTypeIndex[i]:_EventTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _EventTypeNoOp() {
	var x [1]struct{}
	_ = x[EvtZoneChange-(0)]
	_ = x[EvtDeclaredAttacker-(1)]
	_ = x[EvtDeclaredBlocker-(2)]
	_ = x[EvtDamageDealt-(3)]
	_ = x[EvtLifeGained-(4)]
	_ = x[EvtLifeLost-(5)]
	_ = x[EvtCardDrawn-(6)]
	_ = x[EvtSpellCast-(7)]
	_ = x[EvtAbilityActivated-(8)]
	_ = x[EvtAttach-(9)]
	_ = x[EvtDetach-(10)]
	_ = x[EvtUpkeep-(11)]
	_ = x[EvtDrawStep-(12)]
	_ = x[EvtBeginCombat-(13)]
	_ = x[EvtEndStep-(14)]
	_ = x[EvtTapped-(15)]
	_ = x[EvtLandPlayed-(16)]
	_ = x[EvtBlockersDecl-(17)]
	_ = x[EvtEndOfCombat-(18)]
	_ = x[EvtBecameUntapped-(19)]
	_ = x[EvtMainPhase-(20)]
	_ = x[EvtCleanup-(21)]
	_ = x[EvtCreatureBlocks-(22)]
	_ = x[EvtEntersAttacking-(23)]
	_ = x[EvtEntersBlocking-(24)]
	_ = x[EvtScry-(25)]
	_ = x[EvtDiscard-(26)]
	_ = x[EvtSacrifice-(27)]
	_ = x[EvtBecomesTarget-(28)]
	_ = x[EvtAttackersDeclared-(29)]
	_ = x[EvtCombatDamageDealt-(30)]
}

var _EventTypeValues = []EventType{EvtZoneChange, EvtDeclaredAttacker, EvtDeclaredBlocker, EvtDamageDealt, EvtLifeGained, EvtLifeLost, EvtCardDrawn, EvtSpellCast, EvtAbilityActivated, EvtAttach, EvtDetach, EvtUpkeep, EvtDrawStep, EvtBeginCombat, EvtEndStep, EvtTapped, EvtLandPlayed, EvtBlockersDecl, EvtEndOfCombat, EvtBecameUntapped, EvtMainPhase, EvtCleanup, EvtCreatureBlocks, EvtEntersAttacking, EvtEntersBlocking, EvtScry, EvtDiscard, EvtSacrifice, EvtBecomesTarget, EvtAttackersDeclared, EvtCombatDamageDealt}

var _EventTypeNameToValueMap = map[string]EventType{
	_EventTypeName[0:10]:         EvtZoneChange,
	_EventTypeLowerName[0:10]:    EvtZoneChange,
	_EventTypeName[10:26]:        EvtDeclaredAttacker,
	_EventTypeLowerName[10:26]:   EvtDeclaredAttacker,
	_EventTypeName[26:41]:        EvtDeclaredBlocker,
	_EventTypeLowerName[26:41]:   EvtDeclaredBlocker,
	_EventTypeName[41:52]:        EvtDamageDealt,
	_EventTypeLowerName[41:52]:   EvtDamageDealt,
	_EventTypeName[52:62]:        EvtLifeGained,
	_EventTypeLowerName[52:62]:   EvtLifeGained,
	_EventTypeName[62:70]:        EvtLifeLost,
	_EventTypeLowerName[62:70]:   EvtLifeLost,
	_EventTypeName[70:79]:        EvtCardDrawn,
	_EventTypeLowerName[70:79]:   EvtCardDrawn,
	_EventTypeName[79:88]:        EvtSpellCast,
	_EventTypeLowerName[79:88]:   EvtSpellCast,
	_EventTypeName[88:104]:       EvtAbilityActivated,
	_EventTypeLowerName[88:104]:  EvtAbilityActivated,
	_EventTypeName[104:110]:      EvtAttach,
	_EventTypeLowerName[104:110]: EvtAttach,
	_EventTypeName[110:116]:      EvtDetach,
	_EventTypeLowerName[110:116]: EvtDetach,
	_EventTypeName[116:122]:      EvtUpkeep,
	_EventTypeLowerName[116:122]: EvtUpkeep,
	_EventTypeName[122:130]:      EvtDrawStep,
	_EventTypeLowerName[122:130]: EvtDrawStep,
	_EventTypeName[130:141]:      EvtBeginCombat,
	_EventTypeLowerName[130:141]: EvtBeginCombat,
	_EventTypeName[141:148]:      EvtEndStep,
	_EventTypeLowerName[141:148]: EvtEndStep,
	_EventTypeName[148:154]:      EvtTapped,
	_EventTypeLowerName[148:154]: EvtTapped,
	_EventTypeName[154:164]:      EvtLandPlayed,
	_EventTypeLowerName[154:164]: EvtLandPlayed,
	_EventTypeName[164:176]:      EvtBlockersDecl,
	_EventTypeLowerName[164:176]: EvtBlockersDecl,
	_EventTypeName[176:187]:      EvtEndOfCombat,
	_EventTypeLowerName[176:187]: EvtEndOfCombat,
	_EventTypeName[187:201]:      EvtBecameUntapped,
	_EventTypeLowerName[187:201]: EvtBecameUntapped,
	_EventTypeName[201:210]:      EvtMainPhase,
	_EventTypeLowerName[201:210]: EvtMainPhase,
	_EventTypeName[210:217]:      EvtCleanup,
	_EventTypeLowerName[210:217]: EvtCleanup,
	_EventTypeName[217:231]:      EvtCreatureBlocks,
	_EventTypeLowerName[217:231]: EvtCreatureBlocks,
	_EventTypeName[231:246]:      EvtEntersAttacking,
	_EventTypeLowerName[231:246]: EvtEntersAttacking,
	_EventTypeName[246:260]:      EvtEntersBlocking,
	_EventTypeLowerName[246:260]: EvtEntersBlocking,
	_EventTypeName[260:264]:      EvtScry,
	_EventTypeLowerName[260:264]: EvtScry,
	_EventTypeName[264:271]:      EvtDiscard,
	_EventTypeLowerName[264:271]: EvtDiscard,
	_EventTypeName[271:280]:      EvtSacrifice,
	_EventTypeLowerName[271:280]: EvtSacrifice,
	_EventTypeName[280:293]:      EvtBecomesTarget,
	_EventTypeLowerName[280:293]: EvtBecomesTarget,
	_EventTypeName[293:310]:      EvtAttackersDeclared,
	_EventTypeLowerName[293:310]: EvtAttackersDeclared,
	_EventTypeName[310:327]:      EvtCombatDamageDealt,
	_EventTypeLowerName[310:327]: EvtCombatDamageDealt,
}

var _EventTypeNames = []string{
	_EventTypeName[0:10],
	_EventTypeName[10:26],
	_EventTypeName[26:41],
	_EventTypeName[41:52],
	_EventTypeName[52:62],
	_EventTypeName[62:70],
	_EventTypeName[70:79],
	_EventTypeName[79:88],
	_EventTypeName[88:104],
	_EventTypeName[104:110],
	_EventTypeName[110:116],
	_EventTypeName[116:122],
	_EventTypeName[122:130],
	_EventTypeName[130:141],
	_EventTypeName[141:148],
	_EventTypeName[148:154],
	_EventTypeName[154:164],
	_EventTypeName[164:176],
	_EventTypeName[176:187],
	_EventTypeName[187:201],
	_EventTypeName[201:210],
	_EventTypeName[210:217],
	_EventTypeName[217:231],
	_EventTypeName[231:246],
	_EventTypeName[246:260],
	_EventTypeName[260:264],
	_EventTypeName[264:271],
	_EventTypeName[271:280],
	_EventTypeName[280:293],
	_EventTypeName[293:310],
	_EventTypeName[310:327],
}

// EventTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EventTypeString(s string) (EventType, error) {
	if val, ok := _EventTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _EventTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to EventType values", s)
}

// EventTypeValues returns all values of the enum
func EventTypeValues() []EventType {
	return _EventTypeValues
}

// EventTypeStrings returns a slice of all String values of the enum
func EventTypeStrings() []string {
	strs := make([]string, len(_EventTypeNames))
	copy(strs, _EventTypeNames)
	return strs
}

// IsAEventType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i EventType) IsAEventType() bool {
	for _, v := range _EventTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
