// Code generated by "enumer -type=Zone -trimprefix=Zone -output=zone_enumer.go"; DO NOT EDIT.

package core

import (
	"fmt"
	"strings"
)

const _ZoneName = "LibraryHandBattlefieldGraveyardStackExileCommand"

var _ZoneIndex = [...]uint8{0, 7, 11, 22, 31, 36, 41, 48}

const _ZoneLowerName = "libraryhandbattlefieldgraveyardstackexilecommand"

func (i Zone) String() string {
	if i < 0 || i >= Zone(len(_ZoneIndex)-1) {
		return fmt.Sprintf("Zone(%d)", i)
	}
	return _ZoneName[_ZoneIndex[i]:_ZoneIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ZoneNoOp() {
	var x [1]struct{}
	_ = x[ZoneLibrary-(0)]
	_ = x[ZoneHand-(1)]
	_ = x[ZoneBattlefield-(2)]
	_ = x[ZoneGraveyard-(3)]
	_ = x[ZoneStack-(4)]
	_ = x[ZoneExile-(5)]
	_ = x[ZoneCommand-(6)]
}

var _ZoneValues = []Zone{ZoneLibrary, ZoneHand, ZoneBattlefield, ZoneGraveyard, ZoneStack, ZoneExile, ZoneCommand}

var _ZoneNameToValueMap = map[string]Zone{
	_ZoneName[0:7]:        ZoneLibrary,
	_ZoneLowerName[0:7]:   ZoneLibrary,
	_ZoneName[7:11]:       ZoneHand,
	_ZoneLowerName[7:11]:  ZoneHand,
	_ZoneName[11:22]:      ZoneBattlefield,
	_ZoneLowerName[11:22]: ZoneBattlefield,
	_ZoneName[22:31]:      ZoneGraveyard,
	_ZoneLowerName[22:31]: ZoneGraveyard,
	_ZoneName[31:36]:      ZoneStack,
	_ZoneLowerName[31:36]: ZoneStack,
	_ZoneName[36:41]:      ZoneExile,
	_ZoneLowerName[36:41]: ZoneExile,
	_ZoneName[41:48]:      ZoneCommand,
	_ZoneLowerName[41:48]: ZoneCommand,
}

var _ZoneNames = []string{
	_ZoneName[0:7],
	_ZoneName[7:11],
	_ZoneName[11:22],
	_ZoneName[22:31],
	_ZoneName[31:36],
	_ZoneName[36:41],
	_ZoneName[41:48],
}

// ZoneString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ZoneString(s string) (Zone, error) {
	if val, ok := _ZoneNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ZoneNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Zone values", s)
}

// ZoneValues returns all values of the enum
func ZoneValues() []Zone {
	return _ZoneValues
}

// ZoneStrings returns a slice of all String values of the enum
func ZoneStrings() []string {
	strs := make([]string, len(_ZoneNames))
	copy(strs, _ZoneNames)
	return strs
}

// IsAZone returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Zone) IsAZone() bool {
	for _, v := range _ZoneValues {
		if i == v {
			return true
		}
	}
	return false
}
