// Code generated by "enumer -type=ActionType -trimprefix=Action -output=interactive_enumer.go"; DO NOT EDIT.

package interactive

import (
	"fmt"
	"strings"
)

const _ActionTypeName = "PassPlayLandCastSpellActivateAbilitySelectAttackersSelectBlockersUndoAssignCombatDamage"

var _ActionTypeIndex = [...]uint8{0, 4, 12, 21, 36, 51, 65, 69, 87}

const _ActionTypeLowerName = "passplaylandcastspellactivateabilityselectattackersselectblockersundoassigncombatdamage"

func (i ActionType) String() string {
	if i < 0 || i >= ActionType(len(_ActionTypeIndex)-1) {
		return fmt.Sprintf("ActionType(%d)", i)
	}
	return _ActionTypeName[_ActionTypeIndex[i]:_ActionTypeIndex[i+1]]
}

func _ActionTypeNoOp() {
	var x [1]struct{}
	_ = x[ActionPass-(0)]
	_ = x[ActionPlayLand-(1)]
	_ = x[ActionCastSpell-(2)]
	_ = x[ActionActivateAbility-(3)]
	_ = x[ActionSelectAttackers-(4)]
	_ = x[ActionSelectBlockers-(5)]
	_ = x[ActionUndo-(6)]
	_ = x[ActionAssignCombatDamage-(7)]
}

var _ActionTypeValues = []ActionType{ActionPass, ActionPlayLand, ActionCastSpell, ActionActivateAbility, ActionSelectAttackers, ActionSelectBlockers, ActionUndo, ActionAssignCombatDamage}

var _ActionTypeNameToValueMap = map[string]ActionType{
	_ActionTypeName[0:4]:        ActionPass,
	_ActionTypeLowerName[0:4]:   ActionPass,
	_ActionTypeName[4:12]:       ActionPlayLand,
	_ActionTypeLowerName[4:12]:  ActionPlayLand,
	_ActionTypeName[12:21]:      ActionCastSpell,
	_ActionTypeLowerName[12:21]: ActionCastSpell,
	_ActionTypeName[21:36]:      ActionActivateAbility,
	_ActionTypeLowerName[21:36]: ActionActivateAbility,
	_ActionTypeName[36:51]:      ActionSelectAttackers,
	_ActionTypeLowerName[36:51]: ActionSelectAttackers,
	_ActionTypeName[51:65]:      ActionSelectBlockers,
	_ActionTypeLowerName[51:65]: ActionSelectBlockers,
	_ActionTypeName[65:69]:      ActionUndo,
	_ActionTypeLowerName[65:69]: ActionUndo,
	_ActionTypeName[69:87]:      ActionAssignCombatDamage,
	_ActionTypeLowerName[69:87]: ActionAssignCombatDamage,
}

var _ActionTypeNames = []string{
	_ActionTypeName[0:4],
	_ActionTypeName[4:12],
	_ActionTypeName[12:21],
	_ActionTypeName[21:36],
	_ActionTypeName[36:51],
	_ActionTypeName[51:65],
	_ActionTypeName[65:69],
	_ActionTypeName[69:87],
}

// ActionTypeString retrieves an enum value from the enum constants string name.
func ActionTypeString(s string) (ActionType, error) {
	if val, ok := _ActionTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ActionTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ActionType values", s)
}

// ActionTypeValues returns all values of the enum
func ActionTypeValues() []ActionType {
	return _ActionTypeValues
}

// ActionTypeStrings returns a slice of all String values of the enum
func ActionTypeStrings() []string {
	strs := make([]string, len(_ActionTypeNames))
	copy(strs, _ActionTypeNames)
	return strs
}

// IsAActionType returns "true" if the value is listed in the enum definition.
func (i ActionType) IsAActionType() bool {
	for _, v := range _ActionTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
