/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package git.sr.ht/~cdcarter/mage-go/cmd/pylib */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 15 "main.go"

#include <stdlib.h>
#include "abi.h"

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


/* Return type for MageNewGame */
struct MageNewGame_return {
	int64_t r0; /* id */
	char* r1; /* resp */
};
extern struct MageNewGame_return MageNewGame(char* cfgJSON);
extern char* MageState(int64_t id);
extern char* MageLegal(int64_t id);
extern char* MageStep(int64_t id, char* actionJSON);
extern void MageFree(int64_t id);
extern void MageFreeString(char* s);
extern char* MageRegisteredCards();
extern char* MageRegisteredManaCosts();
extern char* MageSetCardNameRows(char* cardNameRowsJSON);
extern MageEncodeResult MageBatchPoll(MageBatchRequest* req, MageBatchPollOutputs* out);
extern MageEncodeResult MageBatchStepByChoice(MageStepChoiceRequest* req);
extern MageEncodeResult MageEncodeBatch(MageBatchRequest* req, MageEncodeConfig* cfg, MageEncodeOutputs* out);

// Stores the borrowed pointers in “tokenTables“ for use by the future
// native text-encoder assembler. Returns 0 on success or a positive error
// code on a wire-format inconsistency. Calling with a nil pointer clears
// the registration.
//
extern int32_t MageRegisterTokenTables(MageTokenTables* tables);

// Returns a JSON summary of the currently registered token tables (sizes
// per category). Used by the Phase-3 round-trip parity test to verify the
// wire format unpacks correctly. Returns "null" if no tables registered.
//
extern char* MageTokenTableSummary();

// Test/debug accessor: returns the JSON-encoded token-id list for a single
// (kind, key) pair. “kind“ is one of:
//
//	0=fragment, 1=turn_step, 2=life_owner, 3=ability, 4=count,
//	5=zone_open, 6=zone_close, 7=action_verb, 8=mana_glyph,
//	9=card_body, 10=card_name, 11=card_ref (single id list).
//
// Two key fields cover all (zero or one used).
//
extern char* MageTokenTableLookup(int32_t kind, int32_t k0, int32_t k1);

extern MageEncodeResult MageEncodeTokensPacked(MageBatchRequest* req, MageEncodeConfig* cfg, MageEncodeOutputs* out, MageTokenAssemblerConfig* tokCfg, MagePackedTokenAssemblerOutputs* packedOut);
extern int64_t MagePendingPlayer(int64_t id);
extern int64_t MageIsOver(int64_t id);
extern char* MageWinner(int64_t id);

#ifdef __cplusplus
}
#endif
