/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/benprew/mage-go/cmd/pylib */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "decision_spec_ffi.go"

#include <stdlib.h>
#include "abi.h"

#line 1 "cgo-generated-wrapper"

#line 15 "main.go"

#include <stdlib.h>
#include "abi.h"

#line 1 "cgo-generated-wrapper"

#line 3 "text_rollout.go"

#include <stdlib.h>
#include "abi.h"

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// MageRegisterDecisionSpecTokens registers the spec-tag ids + digit
// lookup table. Returns 0 on success, nonzero on a wire-format error.
//
extern int32_t MageRegisterDecisionSpecTokens(MageDecisionSpecTokens* tables);
extern void MageReleaseBatchHandle(int64_t handle);

// MageEncodeDecisionSpec emits decision-spec tokens, anchors, and side
// tensors for each row in “req“. Returns a batch handle (via “handleOut“)
// that subsequent MageDecisionMaskNext calls can reference.
//
// This is a sibling of MageEncodeTokensPacked: it does not touch the
// inline-blank assembler outputs and does not need a token-budget. It
// assumes the caller has already invoked MageEncodeTokensPacked on the
// same batch and is supplying the per-row state-token lengths so that
// pointer_anchor_positions can be shifted into the combined stream.
//
extern MageEncodeResult MageEncodeDecisionSpec(MageBatchRequest* req, int32_t* stateTokenLensPtr, MagePackedSpecOutputs* specOut, int64_t* handleOut);

// MageDecisionMaskNext computes per-row vocab + pointer masks for one
// decoder step. Reads the per-row state captured by the most recent
// MageEncodeDecisionSpec call referenced by “batch_handle“.
//
extern int32_t MageDecisionMaskNext(int64_t batchHandle, int32_t* prefixTokensPtr, int32_t* prefixPointersPtr, int32_t* prefixLensPtr, int32_t batchSize, int32_t prefixLenMax, int32_t grammarVocabSizeArg, int32_t nAnchorsMax, uint8_t* outVocabMaskPtr, uint8_t* outPointerMaskPtr);

// MagePackCombinedTokens rewrites the packed token stream produced by
// MageEncodeTokensPacked so that each row's spec tokens (emitted into a side
// buffer by MageEncodeDecisionSpec) are concatenated immediately after that
// row's state tokens. After this call, “packed.token_ids[0:cu_seqlens[B]]“
// holds “state || spec“ for every row in row-major packed layout, with all
// supporting outputs (cu_seqlens, seq_lengths, state_positions,
// card_ref_positions, spec.pointer_anchor_positions) updated to the new
// combined-stream coordinates.
//
// The rewrite is in-place: state tokens are shifted forward (lower row index
// processed last) so the source slice is read before being overwritten by a
// later row's destination. Per-row card_ref_positions get the row's
// cumulative-spec offset added; per-row pointer_anchor_positions (which Go
// previously wrote in row-local combined coords) get the row's new packed
// start added so they share the card-ref convention.
//
// Returns 0 on success, -1 if the combined stream would exceed
// “token_capacity“ (caller must allocate “B * max_tokens“ large enough to
// hold state + spec for every row).
//
extern int32_t MagePackCombinedTokens(int32_t n, int32_t tokenCapacity, int32_t maxCardRefs, MagePackedTokenAssemblerOutputs* packed, MagePackedSpecOutputs* spec);

/* Return type for MageNewGame */
struct MageNewGame_return {
	int64_t r0; /* id */
	char* r1; /* resp */
};
extern struct MageNewGame_return MageNewGame(char* cfgJSON);
extern char* MageState(int64_t id);
extern char* MageLegal(int64_t id);
extern char* MageStep(int64_t id, char* actionJSON);
extern void MageFree(int64_t id);
extern void MageFreeString(char* s);
extern char* MageRegisteredCards(void);
extern char* MageRegisteredManaCosts(void);
extern char* MageSetCardNameRows(char* cardNameRowsJSON);
extern MageEncodeResult MageBatchPoll(MageBatchRequest* req, MageBatchPollOutputs* out);
extern MageEncodeResult MageBatchStepByChoice(MageStepChoiceRequest* req);

// MageBatchStepByDecoderAction applies a batch of decoder-shaped actions to
// the engine. See abi.h::MageDecoderStepRequest for the wire layout. Per-env
// errors are logged and skipped (the rest of the batch advances) — matching
// MageBatchStepByChoice's semantics for a malformed env.
//
extern MageEncodeResult MageBatchStepByDecoderAction(MageDecoderStepRequest* req);
extern MageEncodeResult MageEncodeBatch(MageBatchRequest* req, MageEncodeConfig* cfg, MageEncodeOutputs* out);
extern char* MageNativeTimingSummary(int32_t reset);

// Stores the borrowed pointers in “tokenTables“ for use by the future
// native text-encoder assembler. Returns 0 on success or a positive error
// code on a wire-format inconsistency. Calling with a nil pointer clears
// the registration.
//
extern int32_t MageRegisterTokenTables(MageTokenTables* tables);

// Returns a JSON summary of the currently registered token tables (sizes
// per category). Used by the Phase-3 round-trip parity test to verify the
// wire format unpacks correctly. Returns "null" if no tables registered.
//
extern char* MageTokenTableSummary(void);

// Test/debug accessor: returns the JSON-encoded token-id list for a single
// (kind, key) pair. “kind“ is one of:
//
//	0=fragment, 1=turn_step, 2=life_owner, 3=ability, 4=count,
//	5=zone_open, 6=zone_close, 7=action_verb, 8=mana_glyph,
//	9=card_body, 10=card_name, 11=card_ref (single id list).
//
// Two key fields cover all (zero or one used).
//
extern char* MageTokenTableLookup(int32_t kind, int32_t k0, int32_t k1);
extern char* MageEncodeTimingSummary(int32_t reset);
extern MageEncodeResult MageEncodeTokensPacked(MageBatchRequest* req, MageEncodeConfig* cfg, MageEncodeOutputs* out, MageTokenAssemblerConfig* tokCfg, MagePackedTokenAssemblerOutputs* packedOut);
extern int64_t MagePendingPlayer(int64_t id);
extern int64_t MageIsOver(int64_t id);
extern char* MageWinner(int64_t id);
extern MageEncodeResult MageStartTextRollout(MageTextRolloutStartRequest* req);
extern MageEncodeResult MageAddTextRolloutGames(MageTextRolloutStartRequest* req);
extern MageTextReadyBatchResult MageNextTextInferenceBatch(int64_t maxRows, int64_t timeoutMS, MageTextReadyBatchOutputs* out);
extern MageEncodeResult MageSubmitTextChoices(MageTextChoiceSubmitRequest* req);
extern int32_t MageStopTextRollout(int32_t waitForActive);

#ifdef __cplusplus
}
#endif
